import type { Metadata } from 'next';
import { Cinzel, Lato, Lora, Taviraj } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';


const lora = Lora({
    variable: "--font-lora",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const taviraj = Taviraj({
    variable: "--font-taviraj",
    subsets: ["latin"],
    weight: ["400", "700"],
})

const cinzel = Cinzel({
    variable: "--font-cinzel",
    subsets: ["latin"],
    weight: ["400", "700"],
})

export const metadata: Metadata = {
    title: "Max Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${lora.variable} ${lato.variable} ${taviraj.variable} ${cinzel.variable} antialiased relative pb-200`}
        >
        <Header/>
        {children}
        </body>
        </html>
    );
}
